### ISSUE TITLE
[Flutter Support] DataStore should support a double instead of a float

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-android#1031]
As per this [code](https://github.com/aws-amplify/amplify-android/blob/c425a4f1073b6245cf8fef18096c553e8fec99f2/aws-api-appsync/src/main/java/com/amplifyframework/core/model/types/JavaFieldType.java#L28) and [CLI model generation](https://github.com/aws-amplify/amplify-cli/blob/b26c40f433d7d703878b6df25dd312f5de34afdb/packages/amplify-codegen-appsync-model-plugin/src/scalars/index.ts#L7), amplify-android requires GraphQL `float` type to be `Java`'s `Float` type. Based on [appsync guide ](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) a float is

> The Float scalar type represents signed double-precision fractional values as specified by IEEE 754. 

This means that we lose precision when converting a dart `double` to a java `Float`.

Expectation: amplify-android to support `double` type to properly accommodate the appsync `Float`

Originated from: https://github.com/aws-amplify/amplify-flutter/issues/242

**Comment by jamesonwilliams** [comment]
While this fix seems trivial at first glance, it is more challenging than initially meets the eye. In order to support models that currently use `Float`, we have to do this in a few phases:
1. Conditionally support both `java.lang.Float` and `java.lang.Double` in the library. Choose the type based on the type of the passed data value.
2. Update the CLI to use `java.lang.Double` in the Java language models.
3. Later, remote support for the `java.lang.Float` type.

Note for Flutter integrators: after this change, you should pass `javaClassForValue` as `java.lang.Double`.  The type of the value in the map data should also be `java.lang.Double`.
