### ISSUE TITLE
Is there a way to get a Cognito Authorization Code with Amplify?

### ISSUE THREAD

**Issue by jimenaCabrejas** [aws-amplify/amplify-android#1089]
Hi, I'm a new Android developer, it's the first time I'm using Amplify and I'm using Cognito as my authentication provider. 

Once my user is logged into the application I need to get a Cognito authorization code to do an API call and I was wondering if there is a way of doing it using Amplify. It looks like I can get the access tokens with Auth.fetchAuthSession but I haven't seen how to get an authorization code.

I have seen that I need to use the /oauth2/authorize endpoint to get an authorization code but when I call that endpoint it redirects me to the /login endpoint and the user needs to sign in again. This causes a bit of friction because the user is already logged into the app so the ideal scenario would be that he doesn't need to enter his credentials twice.

So is there a way to get an authorization code for a signed in user?

Thanks and best regards

**Comment by richardmcclellan** [comment]
Hi @jimenaCabrejas, Amplify is designed so that you don't usually need to manipulate credentials at all.  When you use the Amplify [API](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/android) plugin, [DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android) plugin (or any other Amplify plugin), the credentials will automatically be included on all API requests, assuming you have signed in with Amplify [Auth](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android). 

If you are working with an API outside of Amplify, you can access the access token and id token via `Amplify.Auth.fetchAuthSession` as you noted, and as described in [this documentation](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android).

> So is there a way to get an authorization code for a signed in user?

No.  You shouldn't need this though.  The authorization code is obtained and passed to the `/login` endpoint for you if you are using `Amplify.Auth.signInWithWebUI`.  Once logged in, the access token is what should be used for authenticating with your API, not an authorization code.

**Comment by jimenaCabrejas** [comment]
Alright! Thank you so much for the quick reply!!

Best regards!
