### ISSUE TITLE
Question: Recommendation on cli.json

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-android#1164]
Amplify CLI creates a cli.json file in the amplify subdirectory that includes a setting for codegen.
```json
"codegen": {
  "useappsyncmodelgenplugin": true
}
```
With this set to `true` it appears to be using a version of codegen that has been getting the recent updates. It does, however, seem to be missing the switch to use [Double instead of Float](https://github.com/aws-amplify/amplify-cli/pull/6145) supported in #1040. That is the most obvious difference when `useappsyncmodelgenplugin` is `true`. Are there other changes that did not make it to the newer codgen or are there feature flags that I need to add to cli.json to turn on code generation using `Double`?

What is the recommended practice when updating versions of amplify-android in my projects? Should I also always regenerate the models? How do I know if an amplify-android update also requires a CLI update or model regeneration?

**Comment by AaronZyLee** [comment]
@kjones Thanks for reporting the issue. The modelgen package and other `amplify-codegen` related package are migrated to a new repo `amplify-codegen` and the old one will no longer get updated. However, it is a mistake for us that we did not notice a previous PR was still made to the old package. Hence, I just create a new PR and include the change you mentioned. It is recommended that you could set the value to `true` since all the following modelgen changes will only happen in the migrated repo.

As for the sync-up between codegen and sdk libraries, this is a good reminder for us to provide users up-to-date message when releasing new features. We plan to have a message printed by codegen to notify user of the minimal SDK library version. At the meantime, it is also a good practice for SDK libraries that they can include the message of using latest codegen in the release note.

**Comment by kjones** [comment]
Thanks @AaronZyLee - I'll look for a new release of the CLI with the switch back to Double. The idea about the CLI messaging min SDK versions sound like it will provide exactly the information I was looking for regarding SDK vs CLI codegen versioning. Feel free to close this if you don't need it as some sort of placeholder reminder.
