### ISSUE TITLE
Wait for query to complete

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [aws-amplify/amplify-android#1221]
Hi' I was trying to write some code that has to make a request to AppSync every TOT seconds... however, I'm unable to find a way to "wait for the request to be completed" (like an `await` for JS).  
This is my current code: 
```
val op = Amplify.API.query(
    ModelQuery.list(Player::class.java, Player.GAMEROOM.eq(currentPlayer.gameroom)),
    { Log.i("MyAmplifyApp", "Query results ") },
    { Log.e("MyAmplifyApp", "Query failed") }
);
```
And I would like to do something like: 
```
op.waitToComplete()
```

Are there ways to do this? (since you are using OkHTTP 4.9, I'm trying to do something like this: https://stackoverflow.com/a/34597477/12361700)

Obviously this code runs on a separated thread, that is neither the GUI Thread not the main Thread

**Comment by richardmcclellan** [comment]
Hi @AlbertoSinigaglia,

I'd suggest checking out the [Kotlin Coroutine Support](https://docs.amplify.aws/lib/project-setup/coroutines/q/platform/android) guide.   We just released this earlier this week, and it allow you to write code similar to using `await` in JS.  To use it, you'll need to add `com.amplifyframework:core-kotlin:0.1.1` as a dependency, and then make sure you are importing `com.amplifyframework.kotlin.core.Amplify` instead of `com.amplifyframework.core.Amplify`

Then, take a look at the [docs for API.query](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/android), and select the Kotlin - Coroutines (Beta) for a code sample.

**Comment by AlbertoSinigaglia** [comment]
Wow, just in time ahah thank you @richardmcclellan
