### ISSUE TITLE
Ambigous behaviour while querying table

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1270]
Hi, I noticed a strange issue while querying my DynamoDB table with Amplify. Here is my code:

```java
Amplify.DataStore.query(
    Users.class, Where.matches(Users.UID.eq(myUID.trim())),
    items -> {
        if (items.hasNext()) {
            Log.i("Amplify", "should go here");
        } else {
            Log.i("Amplify", "but goes here");
        }
    },
    failure -> Log.e("Amplify", "Could not query DataStore", failure)
);
```

In the `Users` table there is one row corresponding to my user. When I query the table while navigating my app functions the query functions well, and it logs:
```console
should go here
```
but when I uninstall my app, the first time I query the table, it returns no rows and prints
```console
but goes here
```

Can anyone help me with suggestions?

Thanks

**Comment by richardmcclellan** [comment]
Hi @marenero1974, `DataStore.query(...)` returns whatever is in the local SQLite table at the time it is called.  If the sync process is just starting, or is in progress, it does not wait for it to complete before returning, so I'm guessing you are calling `DataStore.query(...)` before the sync process is completed.  Here are two possible solutions for you:

1. Wait for the DataStore "ready" Hub event, which is fired when the sync completes, before calling `DataStore.query(...)`.
```
boolean ready = false;

private void main() { 
    if (ready) {
        query();
    } else {
        queryAfterReady();
    }
}

private void query() {
    Amplify.DataStore.query(Blog.class, 
        result -> { /* Display results on your UI */ }, 
        error -> { }
    );
}

private void queryAfterReady() {
   Amplify.DataStore.start(() -> { }, error -> { });
    Amplify.Hub.subscribe(HubChannel.DATASTORE, 
            hubEvent -> DataStoreChannelEventName.READY.toString().equals(hubEvent.getName()), 
            hubEvent -> {
               ready = true;
                query();
            })
    )
}
```

2. Call `DataStore.query(...)` again each time a new item is synced via `DataStore.observe(...)` 
```
private void main() {
    query()
    observe()
}

private void observe() {
    Amplify.DataStore.observe(Blog.class, 
        () -> {},
        item -> query(),
        error -> {},
        () -> {}
    )
}

private void query() {
    Amplify.DataStore.query(Blog.class, 
        result -> { /* Display results on your UI */ }, 
        error -> { }
    );
}
```

**Comment by marenero1974** [comment]
@richardmcclellan 
i used the first one, but while debugging i inspected the value of hubEvent.getName(), and it returns outboxStatus as the event name instead of ready, so the query won't run, what's wrong?

**Comment by richardmcclellan** [comment]
Hi @marenero1974, `HubChannel.DATASTORE` does return several different types of events, including `DataStoreChannelEventName.READY`, `DataStoreChannelEventName.OUTBOX_STATUS`, and [others](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/android).   In order to determine when the sync is complete, and you can get the full result set via `DataStore.query(...)`,  you need to listen for the `DataStoreChannelEventName.READY` event.  If you don't receive it, it is either because you called `Hub.subscribe(...)` after it fired (in which case, you should call subscribe sooner), or there was an error syncing (check your logcat to see if you can identify any errors).

For the second solution that I proposed, the first call to `DataStore.query(...)` will return 0 results on the first app launch, but for subsequent app launches, the first call will return all results in the local database synced on the previous launch.  For this reason, you should call query each time.  It's possible this could even be all results, if there haven't been any changes on the backend since the previous app launch).

**Comment by marenero1974** [comment]
@richardmcclellan both methods you provided, are not working for me, because both of them take a long time to synchronize the local database, my problem is due to the fact that at login I execute the query on a users table, and I have found that running after a few seconds from the subscribe, my query, then it works , if I quickly run the query, it returns no results.

**Comment by richardmcclellan** [comment]
Hey @marenero1974, I think there are two separate issues that you are running into:

1. Sometimes `query` returns zero results.   The current `query` API simply returns whatever is in the local database at the time that you call it, so if the sync process is in progress, or not yet completed, you'll probably get zero results.    The two workarounds proposed above are the best alternatives to this at this time.  I'm actively working on a new API that should eliminate the need for these workarounds.

2. Even with the workaround, it's too slow.  In your case, I'm guessing that you have multiple models that are syncing before your `User` type, so it takes a while before you get the `User` object.  This is another thing I'm actively thinking about a solution for.  One option is we could update DataStore to prioritize the model that you query as the first model that should be synced.

There is actually one more potential workaround that you could try in the meantime though.   You could query the user via `Amplify.API.query(User.java, User.ID.eq("123"), ...)`, instead of using `DataStore.query(...)`.  This will make an immediate API call to AppSync and return the `User` right away.   The response will not be persisted to DataStore either, via this method.   Use caution with this approach though - when DataStore is enabled for your AppSync API, deleted items will be returned in a query (with the `deleted: true` flag), but the `API.query` method in the library does not currently parse the `_deleted` flag from the response, and therefore you won't have a way to know if the items are deleted.  If you aren't deleting `User` objects, it's probably not an issue though.

**Comment by marenero1974** [comment]
Thanks @richardmcclellan i tryied the API query you suggested, but yes ofcourse it gets also users previously deleted, and so i deleted all items from DynamoDB that where with the _deleted flag, and it's a better solution, but let's keep in touch when your new API is ready, let me know... thanks by now

**Comment by poojamat** [comment]
We added an observe query api to support this. [The documentation is here.](https://docs.amplify.aws/lib/datastore/real-time/q/platform/android/#observe-query-results-in-real-time)
