### ISSUE TITLE
Kotlin Facade: observe() should not be a suspend function

### ISSUE THREAD

**Issue by tiagonuneslx** [aws-amplify/amplify-android#1312]
`suspend fun observe(): Flow<DataStoreItemChange<out Model>>`

A function that returns a Kotlin Flow shouldn't be a suspend function. A Flow instance itself can (and I always find it to be) a non-suspend function, and only the terminal operator is a suspend function (like collect). The current implementation is not at all idiomatic of Kotlin, and in certain cases requires a wrap around in another flow.

An example of a Kotlin Flow, doing some time consuming work (from https://kotlinlang.org/docs/flow.html#flows):
```
fun simple(): Flow<Int> = flow { // flow builder
    for (i in 1..3) {
        delay(100) // pretend we are doing something useful here
        emit(i) // emit next value
    }
}
```

In the current implementation, to get an idiomatic, non-suspend Kotlin Flow:
```
val niceFlow = flow {
        emitAll(Amplify.DataStore.observe(Model::class))
}
```

Edit: This is just what I think from my experience with Kotlin, I've never seen a function like this being suspend and doesn't quite make sense to me... whatever you're doing in the suspend function, it can be done inside the flow builder, or in an intermediate operation on a flow

**Comment by drochetti** [comment]
Hey @tiagonuneslx, thank you so much for raising this. I'll look into this and add to our backlog. If you're willing to submit a PR we would also be happy to take your contribution.

> Is there even a way to stop observing a model's changes?

In the non-coroutine implementation there's a cancellable reference that can be used to stop observing.

---

I believe your points are important and I'll go ahead and file an issue against our docs to increase the level of details of our documentation about `DataStore.observe` in all platforms.

**Comment by tiagonuneslx** [comment]
Hi @drochetti, I'd love to contribute but dont own a Mac and I'm getting this bug on Windows #836

**Comment by richardmcclellan** [comment]
Hi @tiagonuneslx, `observe()` suspends until the observation is "started" (that is, the [`Consumer<Cancelable> onObservationStarted`](https://github.com/aws-amplify/amplify-android/blob/682c9e778adac74c2261bce4de4866c5e255a5eb/core/src/main/java/com/amplifyframework/datastore/DataStoreCategoryBehavior.java#L174) callback is called).  Once started, then it returns a `Flow`.

So, what actually happens while `observe()` is suspended?  Most of the time, nothing - it just returns immediately - unless you call `observe` before DataStore is initialized and started -  then it suspends while creating the SQLiteDB (if it doesn't exist yet), and loading the mutation outbox from SQLite, both of which are asynchronous tasks. 

Essentially, the reason for the current design is so that customers know _when_ observing has started (via the return of the suspend function).

This `onObservationStarted` callback does provide a `Cancelable`.  You should be able to modify your implementation to use this for cancelling observations.

**Comment by tiagonuneslx** [comment]
Hi @richardmcclellan, thanks for the explanation, now it makes perfect sense! Thank you guys for this Kotlin Facade and would love it if you considered adding KMM support to Amplify in the future :smile::tada:
