### ISSUE TITLE
How to switch bucket and region 

### ISSUE THREAD

**Issue by ltdbrave** [aws-amplify/amplify-android#1496]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

1、How to switch bucket and region except by amplifyconfiguration.json
2、How do I get the full path of my uploaded files by callback，example：https://xxx-course-resource135500-dev.s3.ap-southeast-1.amazonaws.com/public/123456

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by changxu0306** [comment]
Hello @ltdbrave ,
1. Switching bucket and region is not supported by Amplify Storage category. You can either use Amplify CLI to reconfigure the storage category, that is, to run `amplify update storage` in command line and generate a new `amplifyconfiguration.json` file. Or you can use [escape hatch](https://docs.amplify.aws/lib/storage/escapehatch/q/platform/android/#private-access) to access `AmazonS3Client` in our low-level SDK.
The S3 client bucket is set by `setBucketAcl`.
The S3 client region is set by:
(a) calling `setRegion` / `configureRegion`
(b) calling `setEndpoint` with a region-specific S3 endpoint. 

I recommend you use Amplify CLI since it's much easier.

2. Upon the onSuccess callback of `uploadFile()`, you can only get the key of the uploaded file. Then you can call `getUrl(String key)` to get the full path. Or append the key to the prefix of the path by referring to the configuration file.

**Comment by ltdbrave** [comment]
how  can i get your low-level SDK？Please provide me with an address，thank you!

**Comment by div5yesh** [comment]
Here is the documentation link that @changxu0306 mentioned: https://docs.amplify.aws/lib/storage/escapehatch/q/platform/android/#private-access

This will allow you to fetch the `AmazonS3Client` object and make calls to our low-level SDK.

**Comment by changxu0306** [comment]
This is the javadoc of our low-level SDK. [https://aws-amplify.github.io/aws-sdk-android/docs/reference/](https://aws-amplify.github.io/aws-sdk-android/docs/reference/)
I'd close this issue for now. You can still post your questions here so that we can follow up.
