### ISSUE TITLE
Amplify.API.mutate for Android Cannot Instantiate Blog

### ISSUE THREAD

**Issue by DannyLyubenov** [aws-amplify/amplify-android#247]
**Describe the bug**
By following the GraphQL instructions of running a Mutation, on the Blog example from the documentation, Blog cannot be instantiated.  

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/android/api
2. Configure GraphQL
3. Implement this method:

```java
private void createBlog() {
    Blog blog = Blog.builder().name("My first blog").build();

    Amplify.API.mutate(
            blog,
            MutationType.CREATE,
            new ResultListener<GraphQLResponse<Blog>>() {
                @Override
                public void onResult(GraphQLResponse<Blog> response) {
                    Log.i("ApiQuickStart", "Added Blog with id: " + response.getData().getId());
                }

                @Override
                public void onError(Throwable throwable) {
                    Log.e("ApiQuickStart", throwable.getMessage());
                }
            }
    );
}
```
**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [9]

**Comment by raphkim** [comment]
Hi @DannyLyubenov ,
Thank you for reaching out to us. Would you be able to provide us with the error log so that we may better assess the issue? Also would you be able to verify that:

* [`amplifyconfiguration.json`](https://aws-amplify.github.io/docs/android/api#authorization-modes) is correctly formatted (this should have been automatically generated)
* Correct API is being used for the mutation (there should only be one API inside amplifyconfiguration.json with the type of "GraphQL")
* API is assigned the correct means of authorization
  * If either Cognito User Pools or IAM is being used, the `AWSMobileClient` must have been initialized beforehand

**Comment by DannyLyubenov** [comment]
Hi @raphkim ,

Thank you for getting back to me. I can confirm that all of my config files are current and AWSMobileClient was instantiated. I was not getting error as such, but rather when following the guide for creating a createBlog(), Blog was not recognised so as a result, it remained red. 

However, I did find a workaround and I implemented the Android SDK 2 instead. Now I can read and write to DynamoDB without a problem. Take care
