### ISSUE TITLE
[API] query with predicate behaves strangely

### ISSUE THREAD

**Issue by raphkim** [aws-amplify/amplify-android#264]
The query in [`CodeGenerationInstrumentationTest#queryListWithPredicate()`](https://github.com/aws-amplify/amplify-android/blob/63532d0eb074f7bb220b41f59f54cd55fc33bb21/aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java#L96) returns an absurd number of query matches (297 total) whereas [`CodeGenerationInstrumentationTest#queryListWithoutPredicate()`](https://github.com/aws-amplify/amplify-android/blob/63532d0eb074f7bb220b41f59f54cd55fc33bb21/aws-api/src/androidTest/java/com/amplifyframework/api/aws/CodeGenerationInstrumentationTest.java#L117) only returns about 10 results total. This is while testing on the same test resource.

**Comment by TrekSoft** [comment]
queryListWithPredicate() is exhibiting correct behavior - there are that many matches for that query because we're currently performing cleanups on inserts (a TODO we had left from the reinvent push). For queryListWithoutPredicate I'd check what's being sent to see if there's a lower limit being put on the query or somehow a condition is being applied.
