### ISSUE TITLE
Fatal Exception: io.reactivex.rxjava3.exceptions.UndeliverableException

### ISSUE THREAD

**Issue by mvishnureddy007** [aws-amplify/amplify-android#2654]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line

//Amplify Framework
    implementation 'com.amplifyframework:core:2.13.0'
    implementation 'com.amplifyframework:aws-api:2.13.0'
    implementation 'com.amplifyframework:aws-datastore:2.13.0'
    implementation 'com.amplifyframework:aws-auth-cognito:2.13.0'
    implementation 'com.amplifyframework:rxbindings:2.13.0'
```

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.21 (Ubuntu 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OS:           Linux 6.2.0-37-generic amd64

```

</details>

### Describe the bug

The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Wanted 1 metadata for item with id = b73c344a-ce0a-44b4-9893-293510a1b992, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Hello,

Can you provide an example schema and replication steps to help reproduce the issue ?

**Comment by mvishnureddy007** [comment]
Hello,
I have integrated amplify aws for chat functionality in my application

These are the following steps
1. Logged into My application and amplify sign is integrated.
2. I have logged out from device so before logged from device I have implemented clearing datastore and signout implemented.
3. I went to offline and search for content in Login page and come back online.
4. I was in login page and trying enter data at that time the app got crash.

**Comment by mattcreaser** [comment]
Hi @mvishnureddy007 could you please provide a full log showing this error, there is probably another upstream error causing the problem.

**Comment by mukszngrl** [comment]
**Same error I observed while delta sync is going on network fluctuates.**

`Fatal Exception: io.reactivex.rxjava3.exceptions.UndeliverableException
The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Failure performing sync query to AppSync., cause=ApiException{message=OkHttp client request failed., cause=java.net.UnknownHostException: Unable to resolve host "d7davpai2nashp7zij5zxwri5e.appsync-api.us-east-1.amazonaws.com": No address associated with hostname, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}

io.reactivex.rxjava3.plugins.RxJavaPlugins.onError (RxJavaPlugins.java:367)
io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError (SingleCreate.java:82)
com.amplifyframework.datastore.storage.sqlite.PersistentModelVersion$$ExternalSyntheticLambda2.accept (Unknown Source:4)
com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0 (AppSyncClient.java:115)
com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda0.accept (Unknown Source:4)
com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure (AppSyncGraphQLOperation.java:163)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:545)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
java.lang.Thread.run (Thread.java:1012)

Caused by com.amplifyframework.datastore.DataStoreException
Failure performing sync query to AppSync.

Caused by com.amplifyframework.api.ApiException
OkHttp client request failed.

Caused by java.net.UnknownHostException
Unable to resolve host "d7davpai2nashp7zij5zxwri5e.appsync-api.us-east-1.amazonaws.com": No address associated with hostname

Caused by android.system.GaiException
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)`

**Comment by tobias-feldmann** [comment]
We also see this error on many devices via the Google Play logs.
But I can't reproduce it on our test devices. We use the latest Amplify version 2.21.0
It would be great if you could open this issue again.

> com.amplifyframework.datastore.storage.sqlite.PersistentModelVersion$$ExternalSyntheticLambda2.accept
Exception io.reactivex.rxjava3.exceptions.UndeliverableException:
  at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError (RxJavaPlugins.java:367)
  at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError (SingleCreate.java:82)
  at com.amplifyframework.datastore.storage.sqlite.PersistentModelVersion$$ExternalSyntheticLambda2.accept
  at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0 (AppSyncClient.java:115)
  at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda0.accept
  at com.amplifyframework.api.aws.MultiAuthAppSyncGraphQLOperation$OkHttpCallback.onFailure (MultiAuthAppSyncGraphQLOperation.java:199)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:535)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)
