### ISSUE TITLE
onResult callbacks has same JVM signature

### ISSUE THREAD

**Issue by Manuramv** [aws-amplify/amplify-android#270]
![Screen Shot 2020-02-18 at 11 40 39 PM](https://user-images.githubusercontent.com/31012185/74751621-7c343100-52a8-11ea-9a17-48d622108dc2.png)

This may not be a very big issue. Got the JVM signature error when tried to implements these two interfaces **Callback<UserStateDetails>,ResultListener<GraphQLResponse<Task>>** 

It shouldn't be a show stopper when we needs to implement multiple APIs or more interface on single activity/class.

**Comment by jamesonwilliams** [comment]
Hi @Manuramv, thanks for your report.

While this issue is distinct, and I believe specific to Kotlin, the situation is reminiscent of when one tries to implement multiple interfaces with different template types, in Java:

```
	static final class ValueConsumer implements Consumer<String>, Consumer<Integer> {
		@Override public void accept(String string) {}
		@Override public void accept(Integer integer) {}
	}
 
	interface Consumer<T> {
		void accept(T value);
	}
```
This code will not compile:
```
error: repeated interface
	static final class ValueConsumer implements Consumer<String>, Consumer<Integer> {
```

So, one work-around is to compose the callbacks into your code, instead of having them be part of your activity directly. That is "My `MainActivity` contains a `Callback` for the `UserStateDetails`, and it contains a `ResultListener` for a `GraphQLResponse<Task>`." This, as opposed to "My `MainActivity` _is a_ `Callback`, and it _is a_ `ResultListener`.

e.g.
```
public final class MainActivity extends BaseActivity {
    ...
    private final ResultListener<GraphQLResponse<Task>> responseListener;
    private final Callback<UserStateDetails> userStateDetailsCallback;
    ...
}
```

Or even:
```
public final class MainActivity extend BaseActivity {
    ...
    private void somewhereInYourCode() {
        // Encapsulate the Amplify stuff here, "fan out" to your business logic, from it.
        Amplify.API.mutate(task, new ResultListener<GraphQLResponse<Task>>() {
            @Override
            public void onResult(GraphQLResponse<Task> response) {
                if (!response.hasErrors()) {
                    // do something when the mutation succeeds
                }
            }
            
            @Override
            public void onError(Throwable error) {
            }
        });
    ...
}
```
