### ISSUE TITLE
24.3.5 was the last version to download full songs

### ISSUE THREAD

**Issue by Gawd21** [aws-amplify/amplify-android#2784]
**Issue Description**
Doesn't download music on any version newer than 24.3.5

**Environment Information**
*Amplify Plugins Information:*
awsDataStorePlugin: 1.37.11
awsAPIPlugin: 1.37.11
AndroidLoggingPlugin: 1.37.11

**Device Information**
Device Manufacturer: OnePlus
Device Model: IN2025
Android System Version: 11
SDK Version: 30
Device is an Emulator: No

**Comment by joon-won** [comment]
Hi @Gawd21, thank you for your report. Could you provide log and a code to reproduce the issue? `24.3.5` doesn't seem like an Amplify version to me.

**Comment by Gawd21** [comment]
Sorry for late reply. This was meant for Amazon Music. As a large number of us are having this issue. I will run the update and then pull the log, if you still want it.

**Comment by tylerjroach** [comment]
This is not the team for Amazon Music. Is there evidence that the issue is with DataStore? There could be a number of other issues outside of Amplify's control. Please reach out to the Amazon Music team with concerns (https://music.amazon.com/help/contact). We work closely with the Music team and if there is a problem discovered within Amplify, they will relay that information to us.
