### ISSUE TITLE
Misleading exception thrown when token refresh failed due to network error

### ISSUE THREAD

**Issue by almosr-mikapaytech** [aws-amplify/amplify-android#2806]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
aws_amplify_version = '2.16.1'
implementation "com.amplifyframework:aws-auth-cognito:$aws_amplify_version"
implementation "com.amplifyframework:aws-analytics-pinpoint:$aws_amplify_version"
implementation "com.amplifyframework:rxbindings:$aws_amplify_version"
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.5
------------------------------------------------------------

Build time:   2023-11-29 14:08:57 UTC
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.9 (Oracle Corporation 17.0.9+11-LTS-201)
OS:           Windows 11 10.0 amd64
```

</details>

### Describe the bug

When identity token expired and refresh token cannot be used due to network error then Amplify throws an unrelated error:

```
Caused by: InvalidUserPoolConfigurationException{message=The user pool configuration is missing or invalid., cause=null, recoverySuggestion=Please check the user pool configuration in your amplifyconfiguration.json file.}
 at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$getCurrentUser$1$1.invokeSuspend(RealAWSCognitoAuthPlugin.kt:1789)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

It is possible to recover from this situation when network access is restored.

### Reproduction steps (if applicable)

1. Sign in using Amplify
2. Wait until identity token expires (or adjust the local time on the device).
3. Disable network (e.g. turn on aeroplane mode).
4. Start the app and try to fetch the user session.

### Code Snippet

```kotlin
// Put your code below this line.
RxAmplify.Auth.fetchAuthSession()
  .subscribe({ Log.d("Session fetch", "Success") }, { error -> Log.e("Session fetch", "Fetch failed", error) })

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by yuhengshs** [comment]
Hi @almosr-mikapaytech ,

Thanks for reporting this issue, our team will take a look and post once we have an update

**Comment by joon-won** [comment]
Hi @almosr-mikapaytech, thank you for providing the code snippet, and the steps. I've followed the steps to trigger fetchAuthSession() after changing the system date to few days later, disconnecting the local environment from the internet. Unfortunately, I was not able to replicate it as I've faced a `UnknownHostException` instead. 

If you can, could you consider providing us Verbose level log with `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))`

**Comment by joon-won** [comment]
Thank you @almosr-mikapaytech, with Verbose turned on you will be able to catch something like `RefreshUserPoolTokens Sending event ThrowError` or `Auth State Change` from `AWSCognitoAuthPlugin` which will help us better understand what's going on. I've tried another run today but was not able to replicate your issue. On my end I'm getting `UnknownException` due to lost internet connection. 

Could you share your AWSCognitoAuthSession Result after removing sensitive information from it?

**Comment by joon-won** [comment]
No worries @almosr-mikapaytech, seems like the error message is now more relevant. If the app won't recover with `fetchAuthSession()` after the network recovers, have you tried using `forceRefresh` option? 
```
AuthFetchSessionOptions options = AuthFetchSessionOptions.builder().forceRefresh(true).build();

RxAmplify.Auth.fetchAuthSession(option)
                                .subscribe(
                                    { result -> Log.i(moduleLoggerCode, "Success\n$result") },
                                    { error -> Log.e(moduleLoggerCode, "Error\n$error") })
```
with `forceRefresh` you can force refresh the internal session

**Comment by vincetran** [comment]
Hi @almosr-mikapaytech, can you provide your `amplifyconfiguration.json` file so we can see how your stack is configured? And to confirm the exact conditions for this issue:

- ID Token has expired
- Refresh Token is still VALID
- Network is down (e.g. airplane mode)
- `fetchAuthSession()`is then called

I ask because we have a couple similar issues for those exact conditions (e.g. #2725 and #2783) but the exception encountered there don't match your exception. (UnknownHostException vs your NotAuthorizedException and InvalidUserPoolConfigurationException)

The only notable difference is also that you're using RxAmplify whereas they're not. Just as another troubleshooting tool, can you try making that call using the Kotlin library instead to see if you see the same error?

**Comment by tylerjroach** [comment]
Hi @almosr-mikapaytech,

I want to try to clarify a few things so we can try to dive deep into the issue. 

Whether you are using standard Amplify callbacks, Kotlin Coroutines, or RxJava, each of these strategies should yield the same error messages. RxJava and Kotlin Coroutines simply wrap around the callback approach. The code paths do not differ. Because of this, I think we can rule out which strategy is used to call amplify.

likely cause ("Token is not from a supported provider of this identity pool.")

**Comment by tylerjroach** [comment]
@almosr-mikapaytech How many times have you seen this issue? I would triple check all of the values on the console side to make sure they match what is being used in amplifyconfiguration.

In researching what this error message means, I came across "This issue usually occurs if the app client used for authenticating the user is different from the app client configured with the identity pool. You may confirm this by checking if the aud value in the identity token is different from what's configured in your identity pool."

**Comment by rBressanS** [comment]
Hi @tylerjroach, I'm a backend developer on the @almosr-mikapaytech team. After enabling the cloud trail for the cognito and management events and with your comments on this thread, we could identify that the problem was caused by the fact that one of our User Pools was not registered as a valid identity provider for our Identity Pool.

It is still weird that Identity Pool errors revoked User Pool tokens, but the issue is solved.

**Comment by tylerjroach** [comment]
Great to hear, thank you for following up to let us know the issue. This helps us troubleshoot future investigations!
