### ISSUE TITLE
Got NotAuthorizedEception when doing global signOut

### ISSUE THREAD

**Issue by preethambogadi** [aws-amplify/amplify-android#2934]
From our app we are calling the following code when doing a logOut operation. 

val options = AuthSignOutOptions.builder()
            .globalSignOut(isGlobalSignOut)
            .build()
        Amplify.Auth.signOut(options)
            {.....}

But getting the exception as shown in screenshot for some users only.
            
            
<img width="1592" alt="Screenshot 2024-10-04 at 2 44 08 PM" src="https://github.com/user-attachments/assets/327ca533-12ae-4266-bdd5-29460409bdbf">

Using the following dependencies

    implementation 'com.amplifyframework:core:2.20.0'
    implementation 'com.amplifyframework:aws-auth-cognito:2.20.0'
    implementation 'com.amplifyframework:aws-api:2.20.0'
    implementation 'com.amazonaws:aws-android-sdk-iot:2.75.2'

**Comment by mattcreaser** [comment]
Thanks for the report @preethambogadi. We will need to investigate the correct behaviour here and get back to you.

**Comment by tylerjroach** [comment]
This looks like it may be expected behavior but I can't fully tell as the logs are cut off.

If the tokens are expired (access token + refresh) then the API calls for revoking token and global sign out will fail (the tokens are already expired).

What is important to realize is that this is just a partial failure. The end result state is still "logged out" with credentials cleared on the device. This is not a fatal exception. This is just a warning log.
