### ISSUE TITLE
Social sign in with Google does not return back to app for users who have never set up chrome and are trying to add their account.

### ISSUE THREAD

**Issue by Jeffrey-Chau-Leo** [aws-amplify/amplify-android#2966]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
com.amplifyframework:core-kotlin:2.14.10
com.amplifyframework:aws-auth-cognito:2.14.10
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------

Build time:   2024-03-22 15:52:46 UTC
Revision:     650af14d7653aa949fce5e886e685efc9cf97c10

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          22.0.1 (Oracle Corporation 22.0.1+8-16)
OS:           Mac OS X 13.5 aarch64


```

</details>

### Describe the bug

For mobile users who have never opened chrome and set it up, when signing in via Google social, they are presented with either `Add account to device` or `User without an account`. The latter will take you to the expected email+pass+2FA flow which upon success will eventually return the user back to the app signed in.

If the user were to `Add account to device`, they instead remain within chrome tabs upon completion of the flow. Clicking on `Continue as {added account}` takes the user to their account settings screen rather than back into the app signed in. 

### Reproduction steps (if applicable)

1. Create new emulator
2. Social sign in via Google
3. Presented with set up flow
4. Select `Add account to device`
5. Finish set up flow (i.e. Google ToS and Privacy Policy, Google services)
6. Step 3 shown (with added account)
7. Select `Continue as {added account}` sends user to account settings page

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Set up flow initial screen
![Screenshot_1734391043](https://github.com/user-attachments/assets/6fb9d2d9-3a1c-4d71-bf72-ca158bb520e2)

**Comment by tylerjroach** [comment]
@Jeffrey-Chau-Leo This would appear to be a bug in Google Chrome and should be reported to the Chrome team. Unfortunately this is not something we can control. We requested the custom tab to open a Cognito link, and the setup process is interfering in that scenario. I tested a few scenarios on my device.

1. Select account already on device - works
2. Select "Use without an account" - works
3. Select to Add a new account to device - fails

This does appear to be an edge case few users would encounter. When calling `signInWithWebUI` or `signInWithSocialWebUI`, we open the default browser (unless another is specified). 

* Most all Android users will already have a Google account signed in on their phone as part of the phone's setup. 
* Most users would likely sign into Chrome with that same account (1, which works), or use without and account (2, which works)
* Its likely a user has already set up Chrome for the first time because it is the default browser on their phone.

This type of scenario may be a bit more common as a developer that may constantly be clearing Chrome app data and using alternate accounts for testing.

**Comment by Jeffrey-Chau-Leo** [comment]
@tylerjroach Thanks for the full analysis, I agree this an edge case and was hoping for some kind quicker resolution on this end instead of reaching out to the Chrome team. I will unlikely follow through with reporting to the Chrome team due to the likelihood of occurrence. 

Thanks again, closing issue.
