### ISSUE TITLE
Updating SDK Core Class Not Found

### ISSUE THREAD

**Issue by atomicalsoftwares** [aws-amplify/amplify-android#347]
Hello,

When I update to:

> implementation 'com.amplifyframework:core:0.10.0'

From:

> implementation 'com.amplifyframework:core:0.9.1'

I get the following class "Not Found":

> com.amplifyframework.core.ResultListener;

**Comment by jpignata** [comment]
Thanks for the report. We're in a preview cycle right now, and as part of that our public API is changing. 0.10.0 introduces major changes to our interface to allow users to pass Lambda expressions instead of using ResultListener. You can find the updated documentation on this on https://docs.amplify.aws/lib/getting-started/setup?platform=android.

**Comment by atomicalsoftwares** [comment]
I am getting errors because these classes are not found:

 com.amplifyframework.core.Immutable;
com.amplifyframework.core.ResultListener;


with  com.amplifyframework.core.Immutable;being part of the generated AmplifyModelProvider.java.

The documentation doesn't explain what needs to be done, I've deleted the generated models and ran amplify codegen model and the same error persists.

**Comment by atomicalsoftwares** [comment]
Update 2:

I passed the Consumer<Iterator<Class>> but the query structure seems to be different as well?

https://docs.amplify.aws/lib/datastore/data-access?platform=android#query-data

Still shows using ResultListener being used as well.

**Comment by jpignata** [comment]
Yes, this is definitely true, and you're experiencing some of the downsides of our preview period and rapid changes happening. Thanks for bearing with us. We're working on updates to this page immediately. You can see our progress in our [docs repo](https://github.com/aws-amplify/docs/pull/1437), and see the fully assembled next version of these docs [on this branch](https://pr-1437.d39agkzf0cwtdz.amplifyapp.com/lib/datastore/getting-started?platform=android).

![](http://www.textfiles.com/underconstruction/RaRainForestCanopy4950construction2.gif)

**Comment by atomicalsoftwares** [comment]
@jpignata thanks for the update and clarification!

How would we resolve the error with the AmplifyModelProvider.java which is auto generated by codegen?

**Comment by atomicalsoftwares** [comment]
Update:

(BUG)

When executing "amplify codegen model" it generates AmplifyModelProvider.java.

The Class:

>  @Override
>    public Set<Class<? extends Model>> models() {
>     final Set<Class<? extends Model>> modifiableSet = new HashSet<>(
>           Arrays.<Class<? extends Model>>asList(VolumeDiscount.class)
>         );
>     
>         return Immutable.of(modifiableSet);
>         
>   }

Is generated referencing Immutable from: `import com.amplifyframework.core.Immutable;`

It should reference: `import com.amplifyframework.util.Immutable;`

Also, A.Studio is suggesting changing:
`
Arrays.<Class<? extends Model>>asList(VolumeDiscount.class)`

To:

`Collections.<Class<? extends Model>>singletonList(VolumeDiscount.class)`

**Comment by jpignata** [comment]
Can you ensure you're using the latest CLI? It seems like this changed recently: https://github.com/aws-amplify/amplify-cli/commit/8bff253010e6adf08670a30250290d552dccb525

**Comment by atomicalsoftwares** [comment]
6.4.1
 is that `npm -v aws-amplify` shows

**Comment by jamesonwilliams** [comment]
> Update 2:
> 
> I passed the Consumer<Iterator> but the query structure seems to be different as well?
> 
> https://docs.amplify.aws/lib/datastore/data-access?platform=android#query-data
> 
> Still shows using ResultListener being used as well.

@atomicalsoftwares Thanks for bearing with us here! Truly do appreciate your feedback, it helps to improve our software and documentation.

@jpignata and I did several spins on [the DataStore docs](https://docs.amplify.aws/lib/datastore/data-access?platform=android), since last update to this thread. Among many other things, it has now been updated to use the `Consumer<T>` and `Action` callbacks, instead of the `ResultListener<T>` callback, as you had previously found it.
