### ISSUE TITLE
Expose callback to know when mutation queue is empty

### ISSUE THREAD

**Issue by michalisAsp** [aws-amplify/amplify-android#360]
it might be useful in some cases to know if all pending mutations have completed before we allow the user to do something else.

We are looking at DataStore.

**Comment by jamesonwilliams** [comment]
Hi @michalisAsp, thanks for the feedback. Are you using the AppSync SDK, or the Amplify DataStore?

**Comment by michalisAsp** [comment]
> Hi @michalisAsp, thanks for the feedback. Are you using the AppSync SDK, or the Amplify DataStore?
I updated the description

**Comment by jamesonwilliams** [comment]
Hey @michalisAsp. Just thought of a couple _work-arounds_ for you.

### Option 1: Query for presence of queue records

__Please note that this _work-around_ uses internal APIs. This approach may break at any incremental release, without warning.__

```
Amplify.DataStore.query(PendingMutation.PersistentRecord.class,
    results -> {
        if (!results.hasNext()) {
            // The queue is empty.
        } else {
            // The queue has outstanding records waiting to be processed.
        }
    }, failure -> {
        // Queue may or may not be empty, we can't tell.
    }
);
```

### Option 2: Listen for publication events on Hub.

We do broadcast an event over the Amplify Hub, whenever a model is successfully uploaded to the cloud.

You could keep a count of how many things you're publishing. Create a `CountDownLatch` with that count. Whenever you see a publication event, count down the latch. When the latch gets to 0, the queue would be empty.

Sketch:
```
// Assume that there is nothing in the queue, to start.
// TODO: How can you be sure?

// To start, you have some models you want to save.
final List<YourModel> yourModels = generateThemSomehow();
final int numberEventsToPublish = yourModels.size();

// Listen for publication events on the Hub.
// Start watching for them before save(), so you'll be sure to "catch" them.
final CountDownLatch latch = new CountDownLatch(numberEventsToPublish);
String publicationEventName = 
    DataStoreChannelEventName.PUBLISHED_TO_CLOUD.toString();
Amplify.Hub.subscribe(HubChannel.DATASTORE,
    anyDataStoreEvent -> publicationEventName.equals(anyDataStoreEvent.getName()),
    matchingEvent -> latch.countDown()
);

// Save the models.
for (YouModel yourModel:  yourModels) {
    Amplify.DataStore.save(model, ok -> {}, failure -> {});
}

// Wait until you see an acknowledgement for all of them.
if (latch.await(5, TimeUnit.SECONDS)) {
    // The queue is clear!
}
```

This approach isn't ideal, since you have to wait on the latch. If some of the data doesn't publish successfully, then you won't see an event, and the latch won't count down all the way.

**Comment by michalisAsp** [comment]
@jamesonwilliams that's great thanks! 

Will give both options a try as soon as I can.
