### ISSUE TITLE
Android: Externalize AWS Configuration File 

### ISSUE THREAD

**Issue by FazalHussain** [aws-amplify/amplify-android#575]
Hi,

I have implemented aws amplify in my android application. It will create `awsconfiguration.json` and all the configuration is there regarding aws cognito pool. But I want to get these things from my server if anything needs to updated in future we can do it and don't need to update the application.

I have checked your documentation but I haven't found any way to get these configuration from server.

Is there any way to get `awsconfiguration.json` file from remote server?

**Comment by jamesonwilliams** [comment]
Hi @FazalHussain!

If you are using the `AWSCognitoAuthPlugin`, authentication configuration will be pulled from an `AmplifyConfiguration` instance, instead of from `awsconfiguration.json`.

By default, the `AmplifyConfiguration` is read from `amplifyconfiguration.json`, when you call [`Amplify.configure(context)`](https://github.com/aws-amplify/amplify-android/blob/master/core/src/main/java/com/amplifyframework/core/Amplify.java#L101-L106).

However, there is an alternate call, [`Amplify.configure(configuration, context)`](https://github.com/aws-amplify/amplify-android/blob/master/core/src/main/java/com/amplifyframework/core/Amplify.java#L110-L116) that you can use to supply a configuration yourself.

When using this alternate configuration call, you'll need an `AmplifyConfiguration` instance. There are several ways to obtain one:
1. The default way, by reading `amplifyconfiguration.json`, in a call to [`fromConfigJson(...)`](https://github.com/aws-amplify/amplify-android/blob/master/core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java#L106-L114).
2. By [providing a configuration `JSONObject` directly](https://github.com/aws-amplify/amplify-android/blob/master/core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java#L67-L76);
3. By providing a map of [per-category configurations](https://github.com/aws-amplify/amplify-android/blob/master/core/src/main/java/com/amplifyframework/core/AmplifyConfiguration.java#L58-L61).

So, in your situation, I would recommend something like:
```
String configJsonFromBackend = obtainConfigFromBackendSomehow();
AmplifyConfiguration amplifyConfiguration =
    AmplifyConfiguration.fromJson(new JSONObject(configJsonFromBackend));
Amplify.configure(amplifyConfiguration, context);
```
