### ISSUE TITLE
RFC: Kotlin Extensions for Amplify Libraries

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/amplify-android#605]
The Amplify Libraries for Android are written in Java. Increasingly, we're hearing from developers that you are using Kotlin. In recognition of this, we would like to provide a more idiomatic interface for using Amplify from Kotlin. We're considering building a Kotlin Extensions library. The extensions would provide a Kotlin-first experience to developers integrating the Amplify Libraries in their Kotlin-based Android applications.

We're requesting your feedback on this general product direction, and have some specific questions:

- Are you building applications in Java or Kotlin?
- If you're using the Amplify Libraries in a Kotlin application, what are the points of friction you've encountered?
- How would you expect to interact with a Kotlin facade for the Amplify Libraries? Are there any patterns you'd prefer to see implemented?

Please comment on this thread with your thoughts, suggestions, nits, complaints, or anything else on your mind. 

Reactions (👍 , 👎 , etc.) are also welcomed, as they help us weigh the relative importance of this work.

Thank you!

**Comment by shichonghuotian** [comment]
I hope amplify can support the coroutine

**Comment by Blu3Parr0t** [comment]
I am building applications in Kotlin. I'm also an Android Contractor. A lot of jobs I get are requiring Kotlin experience due to most companies wanting to migrate to Kotlin. There is still Java needed for maintaining old frameworks that aren't being migrated over, but most new features are being created with Kotlin in mind.

The main friction I'm having right now is making a wrapper utility function that would be able to handle all of Amplify calls from sign up, login, queries, and mutations in a more generic way. Since I'm used to using Retrofit I've been able to pass in suspend functions and wrap them with the ServiceResult sealed class (https://developer.android.com/jetpack/guide). This has helped me to be able to handle all types of calls in a more generic manner in order to catch errors.

Facade could work. As mentioned above the way I'd develop to handle the Amplify calls would be to implement a singleton utility function that would expect a suspend fun and return a Response<T> where that may be for sing up, log in, mutation, queries. There might be more to unpack on how to effectively deliver the payload to a client, but one of the biggest issues we have at least in Android is being able to cover error cases. Most companies want us to implement some sort of mechanism that will catch Errors. That requires us to keep in mind not only when the API is down, but if the API returns null, user is has wireless off, etc. Most companies I've been to have had devs create base model classes that have the error fields and are extended to their unique model of expected data in order to handle false positives from the back end. Outside of that they implement something like this: 

```
object GraphQLHandler {

    suspend fun <T> handleCall(
        call: suspend () -> Response<T>
    ): ServiceResult<T> {
         return try {
             val serviceCall = call()
             val body = serviceCall.awsResponse
             if(body != null){
                 ServiceResult.Success(body)
             } else {
                 ServiceResult.Error(Exception("Null body"))
             }
         } catch (exception: Exception){
             ServiceResult.Error(exception)
         }
    }
}
```

In their repo layer they might call something like a login, sign up, query, mutation:
```
suspend fun logIn(username: String, password: String): ServiceResult<LogInModel> {
        return withContext(dispatchers.IO) {
            GraphQLHandler.handleCall {
                Amplify.Auth.LogIn(
                    username,
                    password
                )
            }
```

Lastly, I'd like to say that most Android Devs use something like Retrofit. Almost all Android Devs are trained or expected to know Retrofit when they join a job. I would keep that in mind when wanting to deliver to the Android system because it will automatically let a lot of developers know exactly how to go about switching a Retrofit component with an Amplify component

**Comment by jamesonwilliams** [comment]
Thanks @Blu3Parr0t & @shichonghuotian for the feedback! In your replies, I see two unrelated feature requests:
1. Make auth calls _cancellable_, and
2. Improve integration with Retrofit.

As far as _Kotlin_ support itself is concerned, here are my thoughts. We will produce another "facade" module, like `rxbindings`, but for Kotlin. I suggest to call it either `ktxbindings` or just `ktx`. The primary goal of this module will be contain wrapper functions. The functions will convert Amplify's vanilla callback-style method signatures into Kotlin suspending functions. 

For example, DataStore's vanilla `save(...)` API can be converted to a suspending function:
```kotlin
suspend fun <T: Model> save(model: T): Unit =
    suspendCoroutine { cont ->
        Amplify.DataStore.save(model,
            { cont.resume(Unit) },
            { cont.resumeWithException(it) }
        )
    }
```

As we saw in the Rx Bindings, the Amplify methods fall generally into three categories:
1. Methods that render a single result (or a void result), and are __not__ cancelable
2. Methods that render a single result (or a void result), but __can be cancelled__
3. Methods that emit streams of values and/or multiple different value types

The `save(...)` example above is of type (1).

API's `mutate` is an example of the second type. It needs a mechanism for cancellation. To achieve this, we can use `suspendCancellableCoroutine` to bridge the gap:
```kotlin
suspend fun <T> mutate(request: GraphQLRequest<T>): GraphQLResponse<T> =
    suspendCancellableCoroutine { cont ->
        val operation = Amplify.API.mutate(request,
            { cont.resume(it) },
            { cont.resumeWithException(it) }
        )
        cont.invokeOnCancellation { operation?.cancel() }
    }
```

When launched in a coroutine scope, this will produce a `Job` that can be `cancel()`ed:
```kotlin
val job = launch {
    val response = mutate(request)
}
job.cancel()
```

Lastly, API's _`subscribe`_ method, and Storage's progress-reporting _`upload`_ and _`download`_ have multiple callback types. Ultimately these multiple responses will need to be enveloped into a single result type, as happens in the Rx Bindings. A `Sequence` or `Channel` might be an appropriate native Kotlin type to return for a multi-valued emitter.

Another important thing to figure out: do we namespace this like `Kamplify.API.mutate(...)`? Or can we use Kotlin extension functions to achieve a clean `val response = Amplify.API.mutate(request)` invocation on the `Amplify` facade itself?

**Comment by aajtodd** [comment]
@jamesonwilliams 

For (1), (2), and (3) that looks like what I would expect I think. Flows are a like a reactive stream from my understanding so makes sense. I would probably want to draw up an actual RFC proposal/design of course to be sure but overall agreed.

As far as naming, I'd probably name it something like `amplify-android-coroutines` or `coroutine-bindings`.

`ktx` is not very descriptive and coroutines in the name follows the integration pattern Kotlin established for going the other way and binding xyz to coroutines:
https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration
https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive

As far as new facade vs extensions, I would go with extensions barring any complications with that route. This is what those kotlinx libraries do as well for marrying coroutines to other frameworks and async primitives.

**Comment by taouichaimaa** [comment]
if only you'd make a detailed tutorial, your documentation for android in general is lackluster to say the least. We shouldn't have to suffer to implement MVVM best practices and use Amplify.
