### ISSUE TITLE
Special characters inside URL path causes REST API to return signature mismatch error

### ISSUE THREAD

**Issue by raphkim** [aws-amplify/amplify-android#668]
Special characters inside url path are being double encoded incorrectly.

When creating a new API request with the following options:
```
RestOptions options = RestOptions.builder()
    .addPath("/this%20path")
    .build();
```

the signer erroneously expects the following:
```
The Canonical String for this request should have been\n'GET\n/devo/this%2020path...
```

and ultimately results in the signature mismatch exception.

**Comment by raphkim** [comment]
If you are experiencing this issue, then please let us know by reacting or commenting on this thread so that we may prioritize it. It would also be much appreciated if you could give us a specific use-case that requires you to use special characters inside the URL path.

**Comment by alebret** [comment]
My initial url is `xxxxxx/Citroën/xxxx`
It's working with other brands without special character, but it’s not work here, the response is `The Canonical String for this request should have been\n'GET\n/xxxxxxxxxxx/Citro%25C3%25ABn/xxxxxx`
I have the feeling that url is too much encoded with `Citro%25C3%25ABn` instead of `Citro%C3%ABn`
