### ISSUE TITLE
Use customised key as primary key for datastore models

### ISSUE THREAD

**Issue by richardissuperman** [aws-amplify/amplify-android#869]
It looks like Amplify codegen will generate an ```ID``` any way even if we already set customised key for model, here's the a sample amplify schema:

```
type Book
@key(fields:["bookId", "customerId"])
{
   bookId : ID!
   customerId : ID!
}

```

in the generated code class, we can still see a ID field:

```
primary final @ModelField(targetType = "ID", isRequired = true) String id
```

And when datastore is storing model data it hard code to check the model's id (since **Model** is an interface which has a getID method):

https://github.com/aws-amplify/amplify-android/blob/7de77fe56dc79ab1c75a154821e3f1b04bb308d2/aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java#L280

And after taking a look at the database table datastore creates, we found the ID is the primary key.

![839748894](https://user-images.githubusercontent.com/5363585/94629597-21b87580-0278-11eb-8085-6fe8cf84e4a7.jpg)

（sorry have to cover other fields）

Do you think its reasonable to let the primary key datastore's table the same with what we setup in the schema?  I also found this is the same across amplify iOS/Android/JS

I saw https://github.com/aws-amplify/amplify-android/issues/846#issuecomment-695140859 , not sure if it already in the roadmap?

Thanks!

**Comment by richardmcclellan** [comment]
I chatted offline with @richardissuperman to understand his use case a little more.  His Android application integrates with a preexisting data model, where the primary keys are not in UUID format (e.g. bar codes, serial numbers, etc.).  Adding another field for a bar code is not sufficient, because DataStore won't ensure uniqueness.  That is, a `DataStore.save` should determine whether to do a create or update mutation based on whether a record with that bar code already exists or not.

**Comment by asyschikov** [comment]
> This use case could be solved by removing the UUIDv4 requirement on the id field.

@richardmcclellan what about the use case of Amazon DynamoDB table having partition key and sort key? DynamoDB is not a key value store...

**Comment by richardmcclellan** [comment]
> > This use case could be solved by removing the UUIDv4 requirement on the id field.
> 
> @richardmcclellan what about the use case of Amazon DynamoDB table having partition key and sort key? DynamoDB is not a key value store...

AppSync currently supports custom primary key and sort key(s).  See [this documentation on the @key annotation](https://docs.amplify.aws/cli/graphql-transformer/key) to learn how to configure your types. 
 
That said, the Amplify API and DataStore libraries currently assume the primary key is always `id`.  To add custom primary key support in the library, we plan to introspect the schema to determine what the custom defined primary key is, and then use it as the primary key on the SQLite tables, as well as for querying relationships between models. 

As for the sort key(s), the libraries will need to include the partition key as well as all sort keys for update/delete mutations, as well as when querying for a single item.

**Comment by ekabiri** [comment]
@richardmcclellan could you please help me to understand this below phrase from @key annotatio documentation:
“Once you are certain that you do not need the old index, remove its @key and deploy the API again.”

my impression is that if we want rename id to another bane as primary key we can first use @key ( fields:[“newname”]) and push to cloud then remove @key and again push. Then when i try it again id becomes prinary key.

**Comment by timatperfectco** [comment]
Definitely a plus-one for a solution for this issue, integrating with backends that we cannot modify the hash key for.

**Comment by tarasowski** [comment]
Any news on that issue? 
How do you create an app where the primaryKey is the organizationId and the range key is the id of the item stored?

**Comment by matriedel** [comment]
I would appreciate such a solution

**Comment by PS-MS** [comment]
Is this still being looked at? I remembered seeing the release notes for v1.37.0 saying that custom primary keys are supported in datastore: https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.37.0

And yet the first time we go to use them, it turns out they're not really support. It turns out that the codegen will still generate a required id field ` private final @ModelField(targetType="ID", isRequired = true) String id;` and any integration with the API plugin for syncing completely breaks:

`DataStoreException{message=DataStore subscriptionProcessor failed to start., cause=GraphQLResponseException{message=Subscription error for ***: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'id' in type '***' is undefined @ 'onCreate***/id'', locations='null', path='null', extensions='null'}]`

**Comment by eeatonaws** [comment]
Support for custom primary keys has been added to Amplify Android. Please update to the latest version of Amplify Android. Documentation on using custom primary keys with DataStore is available [here](https://docs.amplify.aws/lib/datastore/advanced-workflows/q/platform/android/#customize-primary-keys).
