### ISSUE TITLE
Amplify Auth in Android, cannot access admin queries API

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-android#905]
hi
I am using the Amplify Auth category which includes an Admin Queries Api but cannot access the api.

In Postman, I test the endpoint with the GET method: https://xxxxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/dev/getUser/?username=jan, (I have a cognito user called jan that is in the admin group). I include an Authorization header with the users id token as a value. (the id token value works when using it to test the api gateway authorizer in the api gateway console). Postman returns a 401 unauthorized status. Nothing displays in Cloudwatch.

In the Api Gateway console, when testing the api's _any_ resources action, I use these settings: 

method: GET, 
path {proxy}: getUser,
 query strings {proxy}: username=jan, 
headers {proxy}: Authorization:id token

The result indicates "Successfully completed execution", "Method completed with status: 500" but returns "message": "Cannot read property 'claims' of undefined"

The lambda execution is displayed in Cloudwatch.

see attached Api Gateway log file

[api_test_log.txt](https://github.com/aws-amplify/amplify-android/files/5379474/api_test_log.txt)

Appreciate any help.

Thanks

**Comment by richardmcclellan** [comment]
Hi @kannieWeesNie,

Looks like this error is addressed on StackOverflow here: https://stackoverflow.com/questions/42350118/aws-apigateway-lambda-proxy-access-authorizer

If that doesn't help, I'd suggest reaching out to API Gateway directly.  From the Console, click "Feedback" in the bottom left of the screen to submit a question.

Closing as this issue is outside the scope of `amplify-android`.
