### ISSUE TITLE
AmplifyException - UsernameExistsException (Android_

### ISSUE THREAD

**Issue by Anikethc** [aws-amplify/amplify-android#979]
Hello,

I have the `Amplify.Auth.Signup` method with me which signs up the user and if the user already exists, it throws an error toast at you and logs the error in Logcat.

Amplify.Auth.Signup code:

<img width="960" alt="2020-11-22" src="https://user-images.githubusercontent.com/50455489/99904048-8cbd8000-2cee-11eb-8e19-4e7d6f838ba6.png">

If the user is not there in the user pool, I have some code to display (The toast). I don't know where to place the code which will get executed if the user is not found in the user pool. I could try a `Try-Catch` statement, but it doesn't work.

There should have been an `Amplify.Auth.CheckUserWithAttribute` or something like that.

And one more thing, how to delete a user from the user pool in java, android? I searched everywhere, but there is not `Amplify.Auth.DeleteUser` method. There should have been.

Can someone please help me with this? Thanks in advance.

**Comment by richardmcclellan** [comment]
> I don't know where to place the code which will get executed if the user is not found in the user pool.

When the user is _not_ found in the user pool, and no other errors occur, then sign up will succeed, so `onResult` will be called.  So, you can display your toast within the onResult implementation like this:
```
Amplify.Auth.signUp(
    username,
    password,
    options,
    result -> { runOnUiThread(() -> {
         Toast.makeText(getApplicationContext(), "Signup successful", Toast.LENGTH_SHORT).show();
    } ) },
    error -> { runOnUiThread(() -> {
        if(error instanceof AuthException.UsernameExistsException) { 
            Toast.makeText(getApplicationContext(), "Signup failed because username exists.", Toast.LENGTH_SHORT).show();
        } else {
            Toast.makeText(getApplicationContext(), "Signup failed for a different reason.", Toast.LENGTH_SHORT).show();
        }
    } ) }
)
```

> How to delete a user from the user pool in java, android? 

This is currently not supported with Amplify.  You could do it by using the underlying Cognito SDK.  Here's the deleteUser method you would call: https://github.com/aws-amplify/aws-sdk-android/blob/aeef05f60ccaf974101059d816e1d0d6d6f477cd/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/services/cognitoidentityprovider/AmazonCognitoIdentityProviderClient.java#L2932-L2978 

> I searched everywhere, but there is not Amplify.Auth.DeleteUser method. There should have been.

This is generally not a common use case because allowing users to sign out is sufficient - can you describe you use case a little more so we can understand why you would like to delete users from your app?

**Comment by Anikethc** [comment]
Hello @richardmcclellan ,

Actually, my `onResult` which is the result is not working.

When there are no user is my user pool, and I sign them up in my app, it works out fine and there data comes in the user pool, but the toast saying `The user is signed up` is not working, which I put in the `onResult` (result).

If I try signing the same person again, the error toast is showing. This means that only the error part of the signup code is working, not the `onResult` part.

This is my code.

<img width="698" alt="2020-11-23 (2)" src="https://user-images.githubusercontent.com/50455489/99925898-d4cbb980-2d65-11eb-9f7e-dff52820657b.png">
