### ISSUE TITLE
Access Token Obtained from Amplify Framework Doesn't Authorize API Gateway Access

### ISSUE THREAD

**Issue by ChihweiLHBird** [aws-amplify/amplify-android#996]
I followed a guide to create a REST API with Lambda function, and everything
seems fine. I can use the token from the AWS Cognito hosted UI to authorize the
access to the API.

Then, for my Android App, I followed these Amplify guides:
 1. https://docs.amplify.aws/lib/restapi/authz/q/platform/android#cognito-user-pool-authorization
 2. https://docs.amplify.aws/lib/restapi/fetch/q/platform/android

I'm getting this error:

> I/MyAmplifyApp: {"message":"Unauthorized"}

Then, I tried to obtain an access token from Amplify:
```java
Amplify.Auth.fetchAuthSession(
    result -> {
        AWSCognitoAuthSession cognitoAuthSession = (AWSCognitoAuthSession) result;
        if (cognitoAuthSession.getUserPoolTokens().getType() == AuthSessionResult.Type.FAILURE) {
            // Handling no session here.
        }
        String token = cognitoAuthSession.getUserPoolTokens().getValue().getAccessToken();
        Log.d(token);
    },
    error -> Log.e("AuthQuickStart", error.toString())
);
```

I try using that tokent with `curl`:

```bash
curl \
    https://dwj9amdhhb.execute-api.us-east-1.amazonaws.com/default/RestaurantsInfo \
    -H "Authorization: [MYACCESSTOKEN]"
```

It still failed.

Any idea what was the problem? Why the access token obtained from Amplify does
not allow me to access the REST API on AWS?

**Comment by TrekSoft** [comment]
Hey @ChihweiLHBird - am I understanding your issue correctly that you are successfully authenticating with your REST API via Cognito User Pool signing in with HostedUI on Web and now are trying to get the same thing working on Android?

How are you signing in on Android? I think you'd need to sign in with HostedUI there as well to get the custom scopes needed on the token.

**Comment by ChihweiLHBird** [comment]
> Hey @ChihweiLHBird - am I understanding your issue correctly that you are successfully authenticating with your REST API via Cognito User Pool signing in with HostedUI on Web and now are trying to get the same thing working on Android?
> 
> How are you signing in on Android? I think you'd need to sign in with HostedUI there as well to get the custom scopes needed on the token.

I sign in on Android with Amplify's API, not the HostedUI on the web. But I did make both of them be one client on the Cognito.

**Comment by rjuliano** [comment]
> I sign in on Android with Amplify's API, not the HostedUI on the web

I assume you're signing in with the `Amplify.Auth.signIn` API?

> I try using that tokent with curl: ```curl \
    https://dwj9amdhhb.execute-api.us-east-1.amazonaws.com/default/RestaurantsInfo \
    -H "Authorization: [MYACCESSTOKEN]"```

This won't work because you're using a JWT token as the authorization header. The JWT tokens are used to exchange for a set of temporary AWS credentials that can then be used to make calls to AWS. The authorization header uses a signature that's calculated using different parts of the request...that's part of what gets abstracted by our library. Details on the signature process can be found [here](https://docs.aws.amazon.com/es_es/apigateway/api-reference/signing-requests/) if you're interested.

> I'm getting this error:
>   I/MyAmplifyApp: {"message":"Unauthorized"}

Are you getting this error when you attempt to make a call using Amplify.API...?

Assuming that's the case, this is the issue we need to figure out. What version of the Amplify CLI are you running? Which Cognito app client id is in your configuration file: the one that has a secret or the one that doesn't? The one WITHOUT the secret is the one that should be in the `amplifyconfiguration.json`. Depending on what version of the CLI you're using, there was an issue where the wrong app client id was getting added to the config, so that's worth checking as well. To verify this:

- Log in to the AWS console and go to Cognito
- Select your user pool, then to go *App clients*
- Click on *Show Details*. There should be two of them; make sure that the one in your config file is the one without the secret

**Comment by ChihweiLHBird** [comment]
> > I sign in on Android with Amplify's API, not the HostedUI on the web
> 
> I assume you're signing in with the `Amplify.Auth.signIn` API?
> 
> > I try using that tokent with curl: `curl \     https://dwj9amdhhb.execute-api.us-east-1.amazonaws.com/default/RestaurantsInfo \     -H "Authorization: [MYACCESSTOKEN]"`
> 
> This won't work because you're using a JWT token as the authorization header. The JWT tokens are used to exchange for a set of temporary AWS credentials that can then be used to make calls to AWS. The authorization header uses a signature that's calculated using different parts of the request...that's part of what gets abstracted by our library. Details on the signature process can be found [here](https://docs.aws.amazon.com/es_es/apigateway/api-reference/signing-requests/) if you're interested.
> 
> > I'm getting this error:
> > I/MyAmplifyApp: {"message":"Unauthorized"}
> 
> Are you getting this error when you attempt to make a call using Amplify.API...?
> 
> Assuming that's the case, this is the issue we need to figure out. What version of the Amplify CLI are you running? Which Cognito app client id is in your configuration file: the one that has a secret or the one that doesn't? The one WITHOUT the secret is the one that should be in the `amplifyconfiguration.json`. Depending on what version of the CLI you're using, there was an issue where the wrong app client id was getting added to the config, so that's worth checking as well. To verify this:
> 
> * Log in to the AWS console and go to Cognito
> * Select your user pool, then to go _App clients_
> * Click on _Show Details_. There should be two of them; make sure that the one in your config file is the one without the secret

I did try Amplify.API.get after signing in, and it doesn't work...
This is the document I followed, https://docs.amplify.aws/lib/restapi/fetch/q/platform/android

And I did set the authorizationType to be `AMAZON_COGNITO_USER_POOLS` in the config file.
